// Vektiss Voice intake questionnaire — Med Spa / Health & Wellness Clinic template
// Used for clients like Smart Choice Health & Wellness Clinic
// Follows the same Section/Question schema as intake-questions.ts

import type { Section } from "./intake-questions";

export const MEDSPA_INTAKE_SECTIONS: Section[] = [
  {
    id: "basics",
    title: "Business Basics",
    intro: "We may have pre-filled some of this from your website. Please confirm or correct.",
    questions: [
      { id: "business_name", label: "Business legal name", type: "text", prefill: "business_name" },
      { id: "dba", label: "DBA / name used when answering the phone", type: "text" },
      { id: "primary_phone", label: "Primary phone number", type: "text", prefill: "contact_phone" },
      { id: "address", label: "Address", type: "text" },
      { id: "website", label: "Website", type: "text", prefill: "website" },
      { id: "social_media", label: "Social media handles (Instagram, Facebook, etc.)", type: "text" },
      { id: "hours_weekday", label: "Weekday hours (Mon–Fri)", type: "text" },
      { id: "hours_saturday", label: "Saturday hours", type: "text" },
      { id: "hours_sunday", label: "Sunday hours", type: "text" },
      { id: "walk_ins", label: "Do you accept walk-ins, appointments only, or both?", type: "text" },
      { id: "provider_names", label: "Provider / staff names the AI should know (e.g., Dr. Smith, Nurse Tanya)", type: "textarea" },
      { id: "direct_email", label: "Email address for appointment requests or inquiries", type: "text" },
      { id: "online_booking", label: "Do you use an online booking system? If yes, what platform and link?", type: "textarea" },
    ],
  },
  {
    id: "services",
    title: "Services Offered",
    intro: "List all treatments and services so the voice assistant can answer questions accurately.",
    questions: [
      { id: "services_list", label: "Full list of services offered", help: "e.g., IV therapy, B12 shots, weight loss injections, Botox, fillers, lab work, wellness visits", type: "textarea", prefill: "services" },
      {
        id: "service_categories",
        label: "Which of the following does your clinic offer? (select all that apply)",
        type: "multiselect",
        options: [
          "IV Therapy / IV Hydration",
          "B12 Injections",
          "Lipo-B / MIC Injections",
          "Vitamin Injections",
          "Weight Loss Program (GLP-1 / Semaglutide / Tirzepatide)",
          "Medical Weight Loss Consultation",
          "Botox",
          "Dermal Fillers",
          "Lab Work / Bloodwork",
          "Hormone Therapy",
          "Preventative Care / Wellness Visits",
          "Urgent Care / Walk-in Clinic",
          "Travel Clinic / Vaccinations",
          "Other",
        ],
      },
      { id: "services_not_offered", label: "Services you do NOT offer that callers commonly ask about", type: "textarea" },
      { id: "new_patient_requirements", label: "Any requirements for new patients? (e.g., consultation first, labs required before weight loss injections)", type: "textarea" },
      { id: "insurance_accepted", label: "Do you accept insurance? If yes, which providers?", type: "textarea" },
      { id: "cash_pay", label: "Are services primarily cash pay / self-pay?", type: "text" },
    ],
  },
  {
    id: "pricing",
    title: "Pricing & Promotions",
    intro: "This determines what the voice assistant can and cannot quote on the phone.",
    questions: [
      { id: "share_pricing", label: "Should the voice assistant share pricing over the phone?", type: "multiselect", options: ["Yes — share exact prices", "Give general ranges only", "No — direct them to book a consultation"] },
      { id: "iv_pricing", label: "IV Therapy pricing (if applicable)", type: "textarea" },
      { id: "weight_loss_pricing", label: "Weight loss program pricing (if applicable)", type: "textarea" },
      { id: "injection_pricing", label: "B12 / Lipo-B / vitamin injection pricing (if applicable)", type: "textarea" },
      { id: "botox_filler_pricing", label: "Botox / filler pricing (if applicable)", type: "textarea" },
      { id: "other_pricing", label: "Any other service pricing to share", type: "textarea" },
      { id: "promotions", label: "Current specials, packages, or promotions?", type: "textarea" },
      { id: "payment_methods", label: "Accepted payment methods (cash, card, financing, HSA/FSA?)", type: "text" },
      { id: "financing", label: "Financing available? Which provider? Should the assistant mention it?", type: "textarea" },
    ],
  },
  {
    id: "booking",
    title: "Appointment Booking Workflow",
    questions: [
      {
        id: "booking_method",
        label: "How should the voice assistant handle appointment requests?",
        type: "multiselect",
        options: [
          "Collect caller info and transfer to a live person to confirm",
          "Collect caller info and text/notify the team to call back",
          "Direct caller to your online booking link",
          "Collect name, phone, service requested, and preferred time — then confirm via text",
        ],
      },
      {
        id: "appt_fields",
        label: "Information the assistant should collect for every appointment request",
        type: "multiselect",
        options: [
          "Caller's full name",
          "Callback phone number",
          "Date of birth",
          "Service requested",
          "New or returning patient",
          "Preferred date and time",
          "Any known allergies or medical conditions (for weight loss / IV services)",
          "Current medications (for weight loss / IV services)",
          "How did you hear about us?",
        ],
      },
      { id: "appt_other_fields", label: "Any other fields to collect for appointments?", type: "textarea" },
      { id: "consultation_required", label: "Is a consultation required before any services? If yes, which ones?", type: "textarea" },
    ],
  },
  {
    id: "routing",
    title: "Call Routing Rules",
    intro: "This defines what the voice assistant handles vs. what gets transferred to a live person.",
    questions: [
      {
        id: "ai_handles",
        label: "Calls the assistant should HANDLE FULLY (no transfer needed)",
        type: "multiselect",
        options: [
          "Hours and location questions",
          "Services offered (yes/no)",
          "Directions to the clinic",
          "Online booking link",
          "General pricing ranges",
          "Current promotions",
          "New patient intake info",
          "Leaving a message for a callback",
        ],
      },
      { id: "ai_handles_other", label: "Other calls the assistant should handle fully", type: "textarea" },
      {
        id: "ai_transfers",
        label: "Calls the assistant should TRANSFER to a live person",
        type: "multiselect",
        options: [
          "Caller wants to speak to a specific provider or staff member",
          "Caller has a medical question requiring clinical judgment",
          "Caller has a complaint or billing issue",
          "Caller is a vendor or supplier",
          "Caller explicitly asks to speak to a human",
          "Caller is a current patient with questions about their treatment",
        ],
      },
      { id: "ai_transfers_other", label: "Other calls the assistant should transfer", type: "textarea" },
      { id: "transfer_number", label: "Transfer phone number(s) and any routing rules (e.g., different numbers for different call types)", type: "textarea" },
      {
        id: "no_answer_action",
        label: "If no one answers the transfer, the assistant should:",
        type: "multiselect",
        options: [
          "Take a message and promise a callback",
          "Send caller to voicemail",
          "Ask the caller to call back during business hours",
        ],
      },
      {
        id: "after_hours_action",
        label: "After-hours calls — when the clinic is closed, the assistant should:",
        type: "multiselect",
        options: [
          "Take a message with name, number, and reason for calling",
          "Share the online booking link",
          "Provide emergency/urgent care referral information",
        ],
      },
    ],
  },
  {
    id: "personality",
    title: "Agent Personality & Script",
    questions: [
      { id: "agent_name", label: "Agent name (custom name, or just the clinic name?)", type: "text" },
      { id: "greeting_script", label: "Preferred greeting / opening line", help: "e.g., 'Thank you for calling Smart Choice Health & Wellness, this is Aria, how can I help you today?'", type: "textarea" },
      {
        id: "tone",
        label: "Tone",
        type: "multiselect",
        options: [
          "Warm and welcoming",
          "Professional and clinical",
          "Friendly and conversational",
          "Upbeat and energetic",
        ],
      },
      { id: "bilingual", label: "Spanish-speaking callers — should the agent be bilingual?", type: "textarea" },
      { id: "never_say", label: "Anything the agent should NEVER say or topics to avoid?", type: "textarea" },
      { id: "hipaa_note", label: "Any HIPAA-related instructions? (e.g., never confirm patient status, never discuss medical history)", type: "textarea" },
    ],
  },
  {
    id: "sms",
    title: "SMS Follow-Up",
    intro: "If Vektiss Voice SMS is enabled, the assistant can send automated texts after calls.",
    questions: [
      { id: "sms_booking_link", label: "Send booking link via text after the call?", type: "textarea" },
      { id: "sms_thankyou", label: "Send a 'thank you for calling' text?", type: "textarea" },
      { id: "sms_custom_message", label: "Any custom message to include in follow-up texts?", type: "textarea" },
      { id: "sms_from_number", label: "What phone number should SMS come from?", type: "text" },
    ],
  },
  {
    id: "integrations",
    title: "Integrations & Tech Stack",
    questions: [
      { id: "ehr_software", label: "EHR / practice management software (e.g., Jane App, Mindbody, Vagaro, Aesthetic Record, Tebra)", type: "text" },
      { id: "crm", label: "CRM or patient communication platform (e.g., Podium, Birdeye, Klara)", type: "text" },
      { id: "google_business", label: "Google Business Profile — should the assistant reference it for reviews or directions?", type: "text" },
      { id: "recordings_delivery", label: "How would you like call recordings and transcripts delivered? (email, dashboard, both)", type: "textarea" },
    ],
  },
];
