/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalSlugRouteImport } from './routes/proposal.$slug'
import { Route as IntakeTokenRouteImport } from './routes/intake.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardEmailsRouteImport } from './routes/_authenticated/dashboard.emails'
import { Route as AuthenticatedDashboardCallsRouteImport } from './routes/_authenticated/dashboard.calls'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedAdminProposalsRouteImport } from './routes/_authenticated/admin.proposals'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminIntakeRouteImport } from './routes/_authenticated/admin.intake'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedDashboardCallsIdRouteImport } from './routes/_authenticated/dashboard.calls.$id'
import { Route as AuthenticatedAdminIntakeIdRouteImport } from './routes/_authenticated/admin.intake.$id'
import { Route as AuthenticatedAdminClientsSlugRouteImport } from './routes/_authenticated/admin.clients.$slug'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalSlugRoute = ProposalSlugRouteImport.update({
  id: '/proposal/$slug',
  path: '/proposal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeTokenRoute = IntakeTokenRouteImport.update({
  id: '/intake/$token',
  path: '/intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmailsRoute =
  AuthenticatedDashboardEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCallsRoute =
  AuthenticatedDashboardCallsRouteImport.update({
    id: '/calls',
    path: '/calls',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminProposalsRoute =
  AuthenticatedAdminProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntakeRoute =
  AuthenticatedAdminIntakeRouteImport.update({
    id: '/intake',
    path: '/intake',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardCallsIdRoute =
  AuthenticatedDashboardCallsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardCallsRoute,
  } as any)
const AuthenticatedAdminIntakeIdRoute =
  AuthenticatedAdminIntakeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminIntakeRoute,
  } as any)
const AuthenticatedAdminClientsSlugRoute =
  AuthenticatedAdminClientsSlugRouteImport.update({
    id: '/clients/$slug',
    path: '/clients/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/success': typeof SuccessRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/intake/$token': typeof IntakeTokenRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/intake': typeof AuthenticatedAdminIntakeRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/clients/$slug': typeof AuthenticatedAdminClientsSlugRoute
  '/admin/intake/$id': typeof AuthenticatedAdminIntakeIdRoute
  '/dashboard/calls/$id': typeof AuthenticatedDashboardCallsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/success': typeof SuccessRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/intake': typeof AuthenticatedAdminIntakeRouteWithChildren
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/clients/$slug': typeof AuthenticatedAdminClientsSlugRoute
  '/admin/intake/$id': typeof AuthenticatedAdminIntakeIdRoute
  '/dashboard/calls/$id': typeof AuthenticatedDashboardCallsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/success': typeof SuccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/intake/$token': typeof IntakeTokenRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/intake': typeof AuthenticatedAdminIntakeRouteWithChildren
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/calls': typeof AuthenticatedDashboardCallsRouteWithChildren
  '/_authenticated/dashboard/emails': typeof AuthenticatedDashboardEmailsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/admin/clients/$slug': typeof AuthenticatedAdminClientsSlugRoute
  '/_authenticated/admin/intake/$id': typeof AuthenticatedAdminIntakeIdRoute
  '/_authenticated/dashboard/calls/$id': typeof AuthenticatedDashboardCallsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/set-password'
    | '/success'
    | '/admin'
    | '/dashboard'
    | '/intake/$token'
    | '/proposal/$slug'
    | '/admin/analytics'
    | '/admin/intake'
    | '/admin/messages'
    | '/admin/proposals'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/emails'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/clients/$slug'
    | '/admin/intake/$id'
    | '/dashboard/calls/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/set-password'
    | '/success'
    | '/intake/$token'
    | '/proposal/$slug'
    | '/admin/analytics'
    | '/admin/intake'
    | '/admin/messages'
    | '/admin/proposals'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/emails'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/clients/$slug'
    | '/admin/intake/$id'
    | '/dashboard/calls/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/set-password'
    | '/success'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/intake/$token'
    | '/proposal/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/intake'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/proposals'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/calls'
    | '/_authenticated/dashboard/emails'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/admin/clients/$slug'
    | '/_authenticated/admin/intake/$id'
    | '/_authenticated/dashboard/calls/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  IntakeTokenRoute: typeof IntakeTokenRoute
  ProposalSlugRoute: typeof ProposalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$slug': {
      id: '/proposal/$slug'
      path: '/proposal/$slug'
      fullPath: '/proposal/$slug'
      preLoaderRoute: typeof ProposalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$token': {
      id: '/intake/$token'
      path: '/intake/$token'
      fullPath: '/intake/$token'
      preLoaderRoute: typeof IntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/emails': {
      id: '/_authenticated/dashboard/emails'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof AuthenticatedDashboardEmailsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calls': {
      id: '/_authenticated/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof AuthenticatedDashboardCallsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/proposals': {
      id: '/_authenticated/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AuthenticatedAdminProposalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intake': {
      id: '/_authenticated/admin/intake'
      path: '/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AuthenticatedAdminIntakeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/calls/$id': {
      id: '/_authenticated/dashboard/calls/$id'
      path: '/$id'
      fullPath: '/dashboard/calls/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCallsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCallsRoute
    }
    '/_authenticated/admin/intake/$id': {
      id: '/_authenticated/admin/intake/$id'
      path: '/$id'
      fullPath: '/admin/intake/$id'
      preLoaderRoute: typeof AuthenticatedAdminIntakeIdRouteImport
      parentRoute: typeof AuthenticatedAdminIntakeRoute
    }
    '/_authenticated/admin/clients/$slug': {
      id: '/_authenticated/admin/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/admin/clients/$slug'
      preLoaderRoute: typeof AuthenticatedAdminClientsSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminIntakeRouteChildren {
  AuthenticatedAdminIntakeIdRoute: typeof AuthenticatedAdminIntakeIdRoute
}

const AuthenticatedAdminIntakeRouteChildren: AuthenticatedAdminIntakeRouteChildren =
  {
    AuthenticatedAdminIntakeIdRoute: AuthenticatedAdminIntakeIdRoute,
  }

const AuthenticatedAdminIntakeRouteWithChildren =
  AuthenticatedAdminIntakeRoute._addFileChildren(
    AuthenticatedAdminIntakeRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminIntakeRoute: typeof AuthenticatedAdminIntakeRouteWithChildren
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminProposalsRoute: typeof AuthenticatedAdminProposalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsSlugRoute: typeof AuthenticatedAdminClientsSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminIntakeRoute: AuthenticatedAdminIntakeRouteWithChildren,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminProposalsRoute: AuthenticatedAdminProposalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientsSlugRoute: AuthenticatedAdminClientsSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardCallsRouteChildren {
  AuthenticatedDashboardCallsIdRoute: typeof AuthenticatedDashboardCallsIdRoute
}

const AuthenticatedDashboardCallsRouteChildren: AuthenticatedDashboardCallsRouteChildren =
  {
    AuthenticatedDashboardCallsIdRoute: AuthenticatedDashboardCallsIdRoute,
  }

const AuthenticatedDashboardCallsRouteWithChildren =
  AuthenticatedDashboardCallsRoute._addFileChildren(
    AuthenticatedDashboardCallsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCallsRoute: typeof AuthenticatedDashboardCallsRouteWithChildren
  AuthenticatedDashboardEmailsRoute: typeof AuthenticatedDashboardEmailsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardCallsRoute:
      AuthenticatedDashboardCallsRouteWithChildren,
    AuthenticatedDashboardEmailsRoute: AuthenticatedDashboardEmailsRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SetPasswordRoute: SetPasswordRoute,
  SuccessRoute: SuccessRoute,
  IntakeTokenRoute: IntakeTokenRoute,
  ProposalSlugRoute: ProposalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
